# Generated by Django 2.0.6 on 2020-01-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templets', '0003_auto_20191218_1434'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='templet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='templets.Templet', verbose_name='邮件模板'),
        ),
    ]
