# Generated by Django 2.0.6 on 2020-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_templet'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('0', '未开始'), ('1', '执行中'), ('2', '已完成'), ('3', '已结束')], default='0', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='complete_date',
            field=models.DateField(blank=True, verbose_name='完成时间'),
        ),
    ]
