# Generated by Django 2.0.6 on 2020-01-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20200115_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成时间'),
        ),
    ]
