# Generated by Django 2.0.6 on 2020-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20200119_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='complete_date',
            field=models.CharField(blank=True, default='0', max_length=10, null=True, verbose_name='完成耗时'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='launch_date',
            field=models.DateTimeField(blank=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sendby_date',
            field=models.DateTimeField(blank=True, verbose_name='结束时间'),
        ),
    ]
