# Generated by Django 2.0.6 on 2020-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20200212_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='launch_date',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sendby_date',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
    ]
