# Generated by Django 2.0.6 on 2020-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20200213_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='failed_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='发送失败次数'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='opened_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='已读邮件数'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='success_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='发送成功次数'),
        ),
    ]
