# Generated by Django 2.0.6 on 2020-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20200213_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('0', '未开始'), ('1', '执行中'), ('2', '已完成'), ('3', '执行错误')], default='0', max_length=20, verbose_name='任务状态'),
        ),
    ]
