# Generated by Django 2.0.6 on 2020-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0002_auto_20191230_1726'),
        ('campaigns', '0008_auto_20200305_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='server',
        ),
        migrations.AddField(
            model_name='campaign',
            name='servers',
            field=models.ManyToManyField(to='smtp.EmailServer', verbose_name='邮件服务器'),
        ),
    ]
