# Generated by Django 2.0.6 on 2020-03-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20200306_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Group', verbose_name='分组'),
        ),
    ]
