# Generated by Django 2.0.6 on 2020-03-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20200306_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Group', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smtp.EmailHeader', verbose_name='邮件头'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Page', verbose_name='钓鱼页面'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='templet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='templets.Templet', verbose_name='邮件模板'),
        ),
    ]
