# Generated by Django 2.0.6 on 2019-12-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkman',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Department', verbose_name='部门'),
        ),
    ]
