# Generated by Django 2.0.6 on 2019-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_addr', models.CharField(max_length=40, verbose_name='发件人')),
                ('to_addr', models.CharField(max_length=40, verbose_name='收件人')),
            ],
        ),
        migrations.CreateModel(
            name='EmailServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='服务器名称')),
                ('interface', models.CharField(choices=[('1', 'POP3'), ('2', 'SMTP'), ('3', 'IMAP')], max_length=10, verbose_name='服务器类型')),
                ('host', models.CharField(max_length=40, verbose_name='服务器地址')),
                ('port', models.CharField(default='25', max_length=10, verbose_name='端口')),
                ('mail_user', models.CharField(max_length=20, verbose_name='用户名')),
                ('mail_pass', models.CharField(max_length=20, verbose_name='授权口令')),
            ],
        ),
    ]
