# Generated by Django 2.0.6 on 2019-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailheader',
            options={'verbose_name': '邮件头', 'verbose_name_plural': '邮件头'},
        ),
        migrations.AlterModelOptions(
            name='emailserver',
            options={'verbose_name': '邮件服务器', 'verbose_name_plural': '邮件服务器'},
        ),
        migrations.RemoveField(
            model_name='emailheader',
            name='to_addr',
        ),
        migrations.AddField(
            model_name='emailheader',
            name='from_name',
            field=models.CharField(default='Phishing', max_length=40, verbose_name='发件人姓名'),
        ),
        migrations.AddField(
            model_name='emailheader',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='emailheader',
            name='from_addr',
            field=models.CharField(max_length=40, verbose_name='发件人地址'),
        ),
    ]
