# Generated by Django 2.0.6 on 2019-12-18 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('templets', '0002_auto_20191218_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='templet',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templet',
            name='attachments',
            field=models.FileField(blank=True, upload_to='attach/%Y/%M', verbose_name='附件'),
        ),
    ]
