# Generated by Django 2.0.6 on 2019-12-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='页面名称')),
                ('html', models.TextField(verbose_name='页面代码')),
                ('redirect_url', models.URLField(verbose_name='跳转链接')),
                ('capture_username', models.BooleanField(default=False)),
                ('capture_password', models.BooleanField(default=False)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
