# Generated by Django 2.0.6 on 2019-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': '钓鱼页面', 'verbose_name_plural': '钓鱼页面'},
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_url',
            field=models.URLField(blank=True, verbose_name='跳转链接'),
        ),
    ]
