# Generated by Django 2.0.6 on 2020-02-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191218_1040'),
        ('pages', '0002_auto_20191226_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(blank=True, max_length=200, null=True, verbose_name='客户端')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='点击者IP')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Linkman', verbose_name='点击者')),
            ],
            options={
                'verbose_name': '点击记录',
                'verbose_name_plural': '点击记录',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='capture_password',
        ),
        migrations.RemoveField(
            model_name='page',
            name='capture_username',
        ),
        migrations.RemoveField(
            model_name='page',
            name='html',
        ),
    ]
